services:
  - type: cron
    name: hottopic-trigger
    env: python
    # 时区、环境变量写在服务内
    envVars:
      - key: TZ
        value: Asia/Shanghai
    schedule: "*/10 * * * *"
    buildCommand: pip install -r requirements.txt
    startCommand: python trigger.py
    